AllCops:
  Exclude:
    - 'spec/samples/**/*'
    - 'tmp/**/*'

# Allow small arrays of words with quotes
Style/WordArray:
  MinSize: 3

# Allow single-line method definitions
Style/SingleLineMethods:
  Enabled: false

# Always use raise to signal exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Place . on the previous line
Style/DotPosition:
  EnforcedStyle: trailing

# Require empty lines between defs, except for one-line defs
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Enforce GaurdClause if there are 2 or more lines in the body
Style/GuardClause:
  MinBodyLength: 2

# Allow s()
Style/MethodCallParentheses:
  Enabled: false

# Allow multiline block chains
Style/MultilineBlockChain:
  Enabled: false

# Allow Perl-style references to regex matches
Style/PerlBackrefs:
  Enabled: false

inherit_from: .rubocop_todo.yml
