AllCops:
  Exclude:
    - 'spec/samples/**/*'
    - 'tmp/**/*'

# Allow small arrays of words with quotes
Style/WordArray:
  MinSize: 3

# Allow single-line method definitions
Style/SingleLineMethods:
  Enabled: false

inherit_from: .rubocop_todo.yml
