AllCops:
  Exclude:
    - 'spec/samples/**/*'
    - 'tmp/**/*'

# Allow small arrays of words with quotes
Style/WordArray:
  MinSize: 3

# Allow single-line method definitions
Style/SingleLineMethods:
  Enabled: false

# Always use raise to signal exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Place . on the previous line
Style/DotPosition:
  EnforcedStyle: trailing

# Require empty lines between defs, except for one-line defs
Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Allow s()
Style/MethodCallParentheses:
  Enabled: false

# Allow multiline block chains
Style/MultilineBlockChain:
  Enabled: false

# Allow Perl-style references to regex matches
Style/PerlBackrefs:
  Enabled: false

# Following this cop's advice does not yield better-looking code. See
# https://github.com/bbatsov/rubocop/issues/1238
Style/Next:
  Enabled: false

inherit_from: .rubocop_todo.yml
